language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-android-square-stack' ]; then cd .. && eval "mv $currentfolder generator-android-square-stack" && cd generator-android-square-stack; fi
